# -*- coding: utf-8 -*-
"""PROJECT-4-Research Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTMrdFSGTVWHX_Z5BEj-dSZz0eYxv58Z
"""

import os
import pandas as pd

os.environ["OPENAI_API_KEY"] = input("Enter OpenAI API Key: ")

!pip install langchain_openai langchain_core

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

llm=ChatOpenAI()

knowledge_df=pd.read_csv("mock_knowledge.csv")

topics_df=pd.read_csv("topics.csv")

print("Available topics")

print(topics_df["topic"])

topic = input("Enter Topic: ")

if topic in topics_df["topic"].values:
    print("Valid Topic")
else:
    print("Invalid Topic")

"""**CREATING SEACH TOOL**"""

@tool
def search(topic: str):
    """
    Search the mock knowledge base for the given topic.
    """

    for _, row in knowledge_df.iterrows():

        if topic.lower() in row["keyword"].lower():

            return {
                "information": row["snippet"],
                "source": row["source"]
            }

    return {
        "information": "No information found.",
        "source": "N/A"
    }

print(search.invoke({"topic":"ethical AI"}))

"""**CREATING SUMMARIZATION TOOL**"""

@tool
def summarize(text:str)->str:
  """Summarize the search results"""

  message = HumanMessage(
        content=f"""

    Summarize the following information.

{text}

    Give the output in this format:

    topic:

    Summary:

    Key Points:


    """
        )

  response = llm.invoke([message])

  return response.content

topic = "large language models ChatGPT"

search_result = search.invoke({"topic": topic})

summary = summarize.invoke({"text": search_result["information"]})

print(summary)

print("\nSource:",search_result["source"])

"""OPTIONAL OFFLINE FALLBACK"""

@tool
def summarize(text: str) -> str:
    """
    Summarize the search results.
    """

    try:

        message = HumanMessage(
            content=f"""
Summarize the following information.

{text}

Give:
1. Summary
2. Key Points

"""
        )

        response = llm.invoke([message])

        return response.content

    except Exception:

        return f"""
Summary

{text}

Key Points

- API not available
- Offline summary

Sources

Mock Knowledge Base
"""

"""**CREATING A SAVE REPORT TOOL**"""

@tool
def save_report(topic: str, report: str):
    """Saves the generated report to a markdown file."""

    import os

    os.makedirs("output", exist_ok=True)

    filepath = f"output/{topic.replace(' ', '_')}.md"

    with open(filepath, "w", encoding="utf-8") as file:
        file.write(report)

    return filepath

file_path = save_report.invoke({"topic": topic, "report": summary})

print(f"Report saved to {file_path}")

"""**BINDING TOOLS**

TOPIC-"climate agriculture"
"""

llm_with_tools = llm.bind_tools([search,summarize,save_report])

topic = "climate agriculture"
message = HumanMessage(
    content = f"Generate a research report on {topic}"
)

response = llm_with_tools.invoke([message])

print(response.tool_calls)

tool_name = response.tool_calls[0]["name"]

tool_args = response.tool_calls[0]["args"]

if tool_name == "search":

    search_result = search.invoke(tool_args)

    print(search_result)

summary = summarize.invoke({"text": search_result["information"]})

print(summary)
print("\nSources:",search_result["source"])

report = summary + "\n\nSources:\n" + search_result["source"]

file_path = save_report.invoke({"topic":topic,"report":report})
print(file_path)

print("Research Report Generated Successfully")
print("Saved at:", file_path)

"""TOPIC-"renewable energy developing countries"
"""

topic = "renewable energy developing countries"
message = HumanMessage(
    content = f"Generate a research report on {topic}"
)

response = llm_with_tools.invoke([message])

print(response.tool_calls)

tool_name = response.tool_calls[0]["name"]

tool_args = response.tool_calls[0]["args"]

if tool_name == "search":

    search_result = search.invoke(tool_args)

    print(search_result)

summary = summarize.invoke({"text": search_result["information"]})

print(summary)
print("\nSources:",search_result["source"])

report = summary + "\n\nSources:\n" + search_result["source"]

file_path = save_report.invoke({"topic":topic,"report":report})
print(file_path)

print("Research Report Generated Successfully")
print("Saved at:", file_path)

"""TOPIC-"large language models ChatGPT"
"""

topic = "large language models ChatGPT"
message = HumanMessage(
    content = f"Generate a research report on {topic}"
)

response = llm_with_tools.invoke([message])

print(response.tool_calls)

tool_name = response.tool_calls[0]["name"]

tool_args = response.tool_calls[0]["args"]

if tool_name == "search":

    search_result = search.invoke(tool_args)

    print(search_result)

summary = summarize.invoke({"text": search_result["information"]})



print(summary)
print("\nSources:",search_result["source"])

report = summary + "\n\nSources:\n" + search_result["source"]

file_path = save_report.invoke({"topic":topic,"report":report})
print(file_path)

print("Research Report Generated Successfully")
print("Saved at:", file_path)

"""TOPIC-"ethical AI"
"""

topic = "ethical AI"
message = HumanMessage(
    content = f"Generate a research report on {topic}"
)

response = llm_with_tools.invoke([message])

print(response.tool_calls)

tool_name = response.tool_calls[0]["name"]

tool_args = response.tool_calls[0]["args"]

if tool_name == "search":

    search_result = search.invoke(tool_args)

    print(search_result)

summary = summarize.invoke({"text": search_result["information"]})



print(summary)
print("\nSources:",search_result["source"])

report = summary + "\n\nSources:\n" + search_result["source"]

file_path = save_report.invoke({"topic":topic,"report":report})
print(file_path)

print("Research Report Generated Successfully")
print("Saved at:", file_path)

"""TOPIC-"Agentic AI workflow automation"
"""

topic = "agentic AI workflow automation"
message = HumanMessage(
    content = f"Generate a research report on {topic}"
)

response = llm_with_tools.invoke([message])

print(response.tool_calls)

tool_name = response.tool_calls[0]["name"]

tool_args = response.tool_calls[0]["args"]

if tool_name == "search":

    search_result = search.invoke(tool_args)

    print(search_result)

summary = summarize.invoke({"text": search_result["information"]})



print(summary)
print("\nSources:",search_result["source"])

report = summary + "\n\nSources:\n" + search_result["source"]

file_path = save_report.invoke({"topic":topic,"report":report})
print(file_path)

print("Research Report Generated Successfully")
print("Saved at:", file_path)